config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  scope '/admin' do
    resources :users, except: :show
    resources :comments, only: :index
  end
  
  get 'categories/add', to: 'categories#add'
  post 'categories/:id/create', to: 'categories#create'

  resources :categories
  resources :comments, except: [:new, :index]

  delete 'comment/:id/delete' => 'comments#destroy', as: 'delete_comment'

  post "vote/vote" => "votes#vote", as: "vote_opinion"
  patch 'debates/comment/:id/disable' => 'comments#disable', as: 'disable_comment'
  patch 'opinions/:id/disable' => 'opinions#disable', as: 'disable_opinion'

    # resources :debates do
    #   resources :opinions do
    #   	resources :comments
    #   end
    # end
  get 'search', to: 'search#search'
  
  resources :opinions do
    
    post 'create'
    collection do
      get 'search_image'
      post 'query_image'
    end

    resources :debates
  end
  
  resources :debates do
    resources :hoojahs, except: [:index]
  end
  
  # get 'opinions/:opinion_id/debates' => 'debates#new', as: 'new_opinion_debate'  
  # post 'opinions/:opinion_id/debates' => 'debates#create'
  # get 'opinions/:opinion_id/debates/:id' => 'debates#edit', as: 'edit_opinion_debate'

  
  root 'opinions#index'
end

app/models/opinion.rb
# require 'elasticsearch/model'

class Opinion < ActiveRecord::Base
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  mount_uploader :image, OpinionImageUploader

	belongs_to :user
	has_many :comments
	has_many :votes
	has_many :debates

	validates :user_id, :category_id, :option1, :option2, presence: true
	default_scope -> { order(created_at: :desc) }

	def hide
	  self.update(disable: true)
	end

	def show
	  self.update(disable: false)
	end

	def vote_0
		self.votes.where(flag: 0)
	end

	def vote_1
		self.votes.where(flag: 1)
	end

	def vote_2
		self.votes.where(flag: 2)
	end

	def voted?(user_id)
		!self.votes.find_by(user_id: user_id).nil?
	end

	def self.search(query)
	  __elasticsearch__.search(
	  {
	    query: {
		multi_match: {
		  query: query,
		  fields: ['title^10','text']
	      }
		},
		highlight: {
		  pre_tags: ['<em>'],
		  post_tags: ['</em>'],
		    fields: {
			  title: {},
			  text: {}
		    }
		  }
	    }
	)
	end

	def active_comments
		Comment.where(opinion_id: self.id, disable: false)
	end

	# settings index: { number_of_shards: 1 } do
	#   mappings dynamic: 'false' do
	#   	indexes :title, analyzer: 'english', index_options: 'offsets'
	#   	indexes :text, analyzer: 'english'
	#   end
	# end

	# Select featured Opinions to show on index page
end

	# Delete the previous opinion index in Elasticsearch

	# Opinion.__elasticsearch__.client.indices.delete index: Opinion.index_name rescue nil

	# Create the new index with the new mapping

	# Opinion.__elasticsearch__.client.indices.create \
	#   index: Opinion.index_name,
	#   body: { settings: Opinion.settings.to_hash, mappings: Opinion.mappings.to_hash }

 #    #index all opinion records from db to Elasticsearch
 #    Opinion.import

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
	before_action :find_categories
	before_action :find_opinion, only: [:show, :update, :destroy, :disable]
	helper VotesHelper

	# Disable an Opinion post
	def disable
		@opinion = Opinion.find(params[:id])
		@opinion.disable = 1
		if @opinion.save
			redirect_to @opinion, notice: 'Post has been disabled!'
		else
			redirect_to @opinion, notice: 'Error disabling post!'
		end
	end

	# Enable an Opinion post
	def enable
		@opinion = Opinion.find(params[:id])
		@opinion.disable = 0
		if @opinion.save
			redirect_to @opinion, notice: 'Post has been enabled!'
		else
			redirect_to @opinion, notice: 'Error enabling post!'
		end
	end

	# Destroys an Opinion post
	def destroy
		@opinion.destroy
		redirect_to root_path
	end

	# Open search image page for Unsplash
	def search_image
		# @search_image = Opinion.new
		@search_results = []
	end

	# # Query image from Unsplash
	# def query_image
	# 	@search_results = Unsplash::Photo.search(params[:search], rand(1..2), 20)
	# 	render 'search_image'
	# end

	# Query to use with jquery later later later
	def query_image
		@js_custom_turbolink = { 'turbolinks-track' => true, "turbolinks-eval" => false } 
		
		returned = Unsplash::Photo.search(params[:search], rand(1..2), 20)
		@search_results = []
		returned.each do |image|
			@search_results << image.urls
		end
		render json: @search_results
	end

	# Index of hoojah
	def index
		if user_signed_in?
			if current_user.role.name == "Admin" || current_user.role.name == "Moderator"
				@opinions = Opinion.all 
			else
				@opinions = Opinion.where(disable: false)
			end
		else
			@opinions = Opinion.where(disable: false)
		end
	end

	# View individual Opinion post
	def show
		@comments = Comment.where(opinion_id: @opinion)
		@comment = Comment.new
		@debates = Debate.where(opinion_id: @opinion.id)
		@opinions = Opinion.last(5)
		@debate = Debate.new
	end

	# Page to create new Opinion post
	def new
		@opinion = Opinion.new
	end

	# Edit an Opinion post
	def edit
		@opinion = find_opinion
	end 

	# Updates an Opinion post
	def update
		if @opinion.update(post_params)
			redirect_to @opinion, notice: 'Post updated!'
		else
			render 'edit'
		end
	end

	# Creates new Opinion post
	def create
		@opinion = current_user.opinions.new(post_params)

		if @opinion.save
			redirect_to @opinion, notice: 'Successfully created post!'
		else
			render 'new'
		end
	end

	def disable
	  if @opinion.hide
        respond_to do |format|
          format.html {redirect_to @opinion, notice: "The opinion from #{@opinion.user.name} is now hidden."}
          format.js
        end
      end
	end

	private

	def find_opinion
		@opinion = Opinion.find(params[:id])
	end

	def find_categories
		@categories = Category.all
	end

	def post_params
		params.require(:opinion).permit(:user_id, :category_id, :title, :image, :option1, :option2, :disable)
	end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_form.html.slim
= form_for @opinion do |f|
	/ Display error messages if any
	- if @opinion.errors.any?
		#error_explanation
			h2
			= pluralize(@opinion.errors.count, "error")
			|  prevented this post from saving
			ul
				- @opinion.errors.full_messages.each do |msg|
					li = msg

	.form-horizontal
		.form-group
			.col-sm-2.control-label
				= f.label :title
			.col-sm-10
				= f.text_field :title, autofocus: true, class: "form-control"
		.form-group
			.col-sm-2.control-label
				= f.label :category
			.col-sm-10
				= f.select :category_id, options_for_select(Category.all.collect {|p| [p.name, p.id] }), {}, class: "form-control"
		= f.hidden_field :user_id, value: "#{current_user.id}"
	    / = f.hidden_field :opinion_id, value: "#{@opinion_id}"
	    /= link_to "Upload image", "#", id: "upload-image", class: "btn btn-primary"
	    /= link_to "Search from Unsplash.com", "#", id: "search-image", class: "btn btn-primary"
		.form-group
			.col-sm-2.control-label
				= f.label "Upload image"
			.col-sm-10
				= f.file_field :image, class: "form-control"
		.form-group
			#image-box
			/ = f.label :search_image
			/ = link_to 'Search image', "#", onclick: "$('#unsplash-search-box').show();"
			/ = f.hidden_field :image, class: 'image-link'
			/ Will use bootstrap popup later

			/ Placeholder for selected image
			/ br Image selected: 
			.image-placeholder
		.form-group
			.col-sm-2.control-label
				= f.label :option_1
				/ Sets maximum characters to 12
			.col-sm-4
				= f.text_field :option1, maxlength: '12', class: "form-control"
			.col-sm-2.control-label
				= f.label :option_2
				/ Sets maximum characters to 12
			.col-sm-4
				= f.text_field :option2, maxlength: '12', class: "form-control"
		.btn-group
			= f.submit 'Post', class: "btn btn-primary-2 btn-block"

#unsplash-search-box
	= render 'search_image'

app/views/opinions/_search_image.html.slim
= form_tag "/opinions/query_image" do |f|
	/ Display error messages if any
	/ - if @search_result.errors.any?
	/ 	h2
	/ 	= pluralize(@search_result.errors.count, "error")
	/ 	prevented this post from saving
	/ 	ul
	/ 		- @search_result.errors.full_messages.each do |msg|
	/ 			li = msg

	.form-group
		= label_tag :search
		= text_field_tag :search, nil, class: 'search-box'
	.btn-group
		= submit_tag 'Search', class: 'search-button'
	
	.search-result-box
		/ - @search_results.each do |image|
		/ 	.unsplash-thumb
		/ 		= image_tag("#{image.urls["thumb"]}")

app/views/opinions/edit.html.slim
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				h1 Edit Opinion
			.panel-body.padding
				strong Current Image
				br
				= image_tag @opinion.image.url(:thumbnail)
				br
				br
				= render 'form'

app/views/opinions/index.html.slim
#opinions.transition-enabled
	- @opinions.each do |opinion|
		.box.panel.panel-default
			- if opinion.disable == true
				.red-bar
			.panel-heading.opinion_image
				#image-border
					- if opinion.image.url.nil?
						= link_to (image_tag "default_image.png"), opinion
					-else
						= link_to (image_tag opinion.image_url(:thumbnail)), opinion 
				.panel-title
					.panel-container
						h2.text-center
							= link_to "#{opinion.title[0..120].gsub(/\s\w+\s*$/,'...')}", opinion
						.panel-vote
							= link_to opinion.option1, vote_opinion_path(id: opinion.id, flag: 1), method: :post, class: "option1"
							= link_to "Neutral", vote_opinion_path(id: opinion.id, flag: 0), method: :post, class: "neutral"
							= link_to opinion.option2, vote_opinion_path(id: opinion.id, flag: 2), method: :post, class: "option2"
			.panel-body
				- unless opinion.votes.all.empty?
					.percentage-bar.text-center
						- if opinion.vote_1.count != nil && opinion.vote_1.count > 0
							<span style="width: #{(opinion.votes.where(flag: 1).count) == nil ? 0 : (opinion.votes.where(flag: 1).count).percentage_of(opinion.votes.count)}%;" class="opinion1-bar bg-blue">#{(opinion.votes.where(flag: 1).count) == nil ? 0 : (opinion.votes.where(flag: 1).count).percentage_of(opinion.votes.count).round(2)}%</span>
						- if opinion.vote_0.count != nil && opinion.vote_0.count > 0
							<span style="width: #{(opinion.votes.where(flag: 0).count) == nil ? 0 : (opinion.votes.where(flag: 0).count).percentage_of(opinion.votes.count)}%;" class="neutral-bar bg-orange">#{(opinion.votes.where(flag: 0).count) == nil ? 0 : (opinion.votes.where(flag: 0).count).percentage_of(opinion.votes.count).round(2)}%</span>
						- if opinion.vote_2.count != nil && opinion.vote_2.count > 0
							<span style="width: #{(opinion.votes.where(flag: 2).count) == nil ? 0 : (opinion.votes.where(flag: 2).count).percentage_of(opinion.votes.count)}%;" class="opinion2-bar bg-green">#{(opinion.votes.where(flag: 2).count) == nil ? 0 : (opinion.votes.where(flag: 2).count).percentage_of(opinion.votes.count).round(2)}%</span>
				/ h2 
				/ 	= link_to "#{opinion.title}", opinion
				/ .row
				/ 	.btn-group
				/ 		ruby: 
				/ 			btns = ["btn-warning", "btn-primary", "btn-success"]
				/ 			unless current_user.nil? || (vote = current_user.votes.find_by(opinion_id: opinion.id)).nil?
				/ 				button_colors = ["btn-default", "btn-default", "btn-default"]
				/ 				button_colors[vote.flag] = btns[vote.flag]
				/ 			else
				/ 				button_colors = btns
				/ 			end

				/ 		= link_to opinion.option1, vote_opinion_path(id: opinion.id, flag: 1), method: :post, class: "btn " + button_colors[1]
				/ 		= link_to "Neutral", vote_opinion_path(id: opinion.id, flag: 0), method: :post, class: "btn " + button_colors[0]
				/ 		= link_to opinion.option2, vote_opinion_path(id: opinion.id, flag: 2), method: :post, class: "btn " + button_colors[2]
				/ .row.text-center
				/ 	.col-md-12
				/ 		.pull-left
				/ 			h5.color-primary
				/ 				= pluralize(opinion.votes.where(flag: 1).count, "vote")
				/ 		.text-center
				/ 			h5.color-warning
				/ 				= pluralize(opinion.votes.where(flag: 0).count, "vote")
				/ 		.pull-right
				/ 			h5.color-success
				/ 				= pluralize(opinion.votes.where(flag: 2).count, "vote")
				p.user
				= pluralize(opinion.active_comments.count, "comment")
			.panel-footer
				p #foodporn #malaysia #cat

app/views/opinions/new.html.slim
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				h1 Add new opinion
			.panel-body.padding
				- if can? :create, @opinion
					= render 'form'
				- else
					  p
					    | You must #{link_to "Login", new_user_session_path} to post a new opinion

app/views/opinions/search_image.html.slim
h1 Search image
= render 'search_image'

app/views/opinions/show.html.slim
#opinion_show.row
	.col-md-9
		.panel.panel-default
			.panel-heading.opinion_image
				#image-border
					.btn-toolbar.btn-group.debate-edit-delete
						- if can? :update, @opinion
							= link_to edit_comment_path(@opinion), class: "btn btn-default" do
									<span class="glyphicon glyphicon-pencil"></span>
							= link_to disable_comment_path(@opinion), class: "btn btn-default", method: :patch, data: {confirm: "Are you sure you want to delete this debate?"} do
								<span class="glyphicon glyphicon-trash"></span>
						- if can? :destroy, @opinion
							= link_to @opinion, class: "btn btn-danger", method: :delete, data: {confirm: "(Admin) Are you sure you want to delete this opinion (for real)?"} do
								<span class="glyphicon glyphicon-remove"></span>
					- if @opinion.image.url.nil?
						= link_to (image_tag "default_image.png"), @opinion
					- else
						= link_to (image_tag @opinion.image_url), @opinion 
				.panel-title
					.panel-container
						h2.text-center
							= @opinion.title
						.panel-vote
							= link_to @opinion.option1, vote_opinion_path(id: @opinion.id, flag: 1), method: :post, class: "option1"
							= link_to "Neutral", vote_opinion_path(id: @opinion.id, flag: 0), method: :post, class: "neutral"
							= link_to @opinion.option2, vote_opinion_path(id: @opinion.id, flag: 2), method: :post, class: "option2"
			.panel-body
				- unless @opinion.votes.all.empty?
					.percentage-bar.text-center
						- if @opinion.vote_1.count != nil && @opinion.vote_1.count > 0
							<span style="width: #{(@opinion.vote_1.count) == nil ? 0 : (@opinion.vote_1.count).percentage_of(@opinion.votes.count)}%;" class="opinion1-bar bg-blue">#{(@opinion.vote_1.count) == nil ? 0 : (@opinion.vote_1.count).percentage_of(@opinion.votes.count).round(2)}%</span>
						- if @opinion.vote_0.count != nil && @opinion.vote_0.count > 0
							<span style="width: #{(@opinion.vote_0.count) == nil ? 0 : (@opinion.vote_0.count).percentage_of(@opinion.votes.count)}%;" class="neutral-bar bg-orange">#{(@opinion.vote_0.count) == nil ? 0 : (@opinion.vote_0.count).percentage_of(@opinion.votes.count).round(2)}%</span>
						- if @opinion.vote_2.count != nil && @opinion.vote_2.count > 0
							<span style="width: #{(@opinion.vote_2.count) == nil ? 0 : (@opinion.vote_2.count).percentage_of(@opinion.votes.count)}%;" class="opinion2-bar bg-green">#{(@opinion.vote_2.count) == nil ? 0 : (@opinion.vote_2.count).percentage_of(@opinion.votes.count).round(2)}%</span>
				/ - unless @debates.empty?
				/ 	.row
				/ 		.col-md-12
				/ 			h3 Latest Debates
				/ 			.row
				/ 				.col-md-5
				/ 					|	Proposer
				/ 				.col-md-5
				/ 					| Contender
				/ 				.col-md-2
				/ 				- @debates.each do |debate|
				/ 					.row
				/ 						.col-md-5
				/ 							#debate_show
				/ 								.bg-blue.user.center
				/ 									.picture
				/ 										= image_tag debate.user_pro.display_avatar, alt: "#{debate.user_pro.name}'s avatar"
				/ 							= debate.user_pro.name
				/ 						.col-md-5
				/ 							= image_tag debate.user_con.display_avatar, alt: "#{debate.user_con.name}'s avatar", class: 'avatar'
				/ 							= debate.user_con.name
				/ 						.col-md-2
				/ 							= link_to "Go to debate", [@opinion, debate], class: "btn-sm btn-primary"
			.panel-footer
				.pull-left posted by <a href="#{user_path(@opinion.user)}">#{@opinion.user.name}</a> #{time_ago_in_words(@opinion.created_at)} ago
				.btn-toolbar.btn-group.pull-right
					- if can? :create, @debate
						= link_to "Create Debate", new_opinion_debate_path(@opinion), class: "btn btn-primary-2"
					- if can? :update, @opinion	
						= link_to "Edit", edit_opinion_path(@opinion), class: "btn btn-default"
						= link_to "Delete", disable_opinion_path(@opinion), method: :patch, class: "btn-group btn btn-default"
					- if can? :destroy, @opinion	
						= link_to "Erase", opinion_path(@opinion), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
				.clearfix
			.panel-body.padding
				- if can? :create, @comment
					= render 'comments/form'
				- else
					p
					| You must #{link_to "Login", new_user_session_path} before you can comment
		    ol.comments
			  	= render @comments
	.col-md-3
		- unless @debates.empty?
			.panel.panel-default
				.panel-body.padding
					h3 Latest Debates
					- @debates.each do |debate|
						#debate_show
							.user
								.row
									.col-md-4
										.picture
											= image_tag debate.user_pro.display_avatar, alt: "#{debate.user_pro.name}'s avatar"
									.col-md-4
									.col-md-4
										.picture
											= image_tag debate.user_con.display_avatar, alt: "#{debate.user_con.name}'s avatar"
								.row
									.col-md-4
										= debate.user_pro.name
									.col-md-4
										h3 VS
									.col-md-4
										= debate.user_con.name
						= link_to "Go to debate", [@opinion, debate], class: "btn-sm btn-primary-2"
						hr
		.panel.panel-default
			.panel-body.padding
				h3 Latest Opinions
				ul.list-group
					- @opinions.each_with_index do |opinion, index|
						- if index < 4
							li.list-group-item.footer 
								= link_to opinion.title, opinion
						- else
							li.list-group-item.footer-no-bottom = link_to opinion.title, opinion