config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  scope '/admin' do
    resources :users, except: :show
    resources :comments, only: :index
  end
  
  get 'categories/add', to: 'categories#add'
  post 'categories/:id/create', to: 'categories#create'

  resources :categories
  resources :comments, except: [:new, :index]

  delete 'comment/:id/delete' => 'comments#destroy', as: 'delete_comment'

  post "vote/vote" => "votes#vote", as: "vote_opinion"
  patch 'debates/comment/:id/disable' => 'comments#disable', as: 'disable_comment'
  patch 'opinions/:id/disable' => 'opinions#disable', as: 'disable_opinion'

    # resources :debates do
    #   resources :opinions do
    #   	resources :comments
    #   end
    # end
  get 'search', to: 'search#search'
  
  resources :opinions do
    
    post 'create'
    collection do
      get 'search_image'
      post 'query_image'
    end

    resources :debates
  end
  
  resources :debates do
    resources :hoojahs, except: [:index]
  end
  
  # get 'opinions/:opinion_id/debates' => 'debates#new', as: 'new_opinion_debate'  
  # post 'opinions/:opinion_id/debates' => 'debates#create'
  # get 'opinions/:opinion_id/debates/:id' => 'debates#edit', as: 'edit_opinion_debate'

  
  root 'opinions#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  
	belongs_to :role
  has_many :opinions
  has_many :comments
  has_many :debates
  has_many :hoojahs
  has_many :votes
  has_many :invitations

	before_save :assign_role
	before_save :generate_identicon

	def assign_role
		self.role = Role.find_by name: "Regular" if self.role.nil?
	end

	def generate_identicon
		self.avatar = Identicon.data_url_for self.email if self.avatar.nil?
	end

	def admin?
    self.role.name == "Admin"
  end

  def moderator?
  	self.role.name == "Moderator"
  end

  def regular?
  	self.role.name == "Regular"
  end

  def display_avatar
    if self.avatar.url.nil?
      "default_avatar.png"
    else
      self.avatar.url
    end
  end

  def debates_count
    Debate.where(user_pro_id: self.id).count + Debate.where(user_con_id: self.id).count
  end

  def opinions_count
    Opinion.where(user_id: self.id).count
  end

  def votes_count
    Vote.where(user_id: self.id).count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:role_id, :name, :about, :avatar, :location, :gender, :birthday, :vote_count, :opinion_count, :debate_count, :karma, :disable, :email, :encrypted_password, :reset_password_token, :sign_in_count, :current_sign_in_ip, :last_sign_in_ip)
    end
end

app/helpers/users_helper.rb
module UsersHelper

	def check_and_fill(data)
		unless data.nil?
			data
		else
			"This field is empty"
		end
	end

	def find_debate(user)
		@debates = []

		Debate.where(user_pro_id: user.id).each do |debate|
			@debates << debate
		end

		Debate.where(user_con_id: user.id).each do |debate|
			@debates << debate
		end

		@debates
	end

end

app/views/users/_comments.html.slim
.tab-pane#user_comments
	- unless (comments = @user.comments).count == 0
		- comments.each do |comment|
			.row.user_comment
				.col-md-4
					= comment.opinion.title
				.col-md-8
					= comment.text
	- else
		p You have no comments.

app/views/users/_debates.html.slim
.tab-pane#user_debates
	- unless (debates = find_debate(@user)).count == 0
		- debates.each do |debate|
			.row.user_debate
				.col-md-3
					= debate.opinion.title
				.col-md-3
					= User.find(debate.user_pro_id).name
				.col-md-3
					= User.find(debate.user_con_id).name
				.col-md-3
					- unless debate.winner_id.nil?
						= User.find(debate.winner_id).name
					- else
						= "No winners yet"
	- else
		p You have no debates.

app/views/users/_form.html.slim
= form_for @user do |f|
	- if @user.errors.any?
		#error_explanation
			h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
			ul
				- @user.errors.full_messages.each do |message|
					li = message
	.form-horizontal
		.form-group
			.col-sm-2.control-label
				= f.label :email
			.col-sm-10
				= f.email_field :email, class: "form-control", autofocus: true

		/- if devise_mapping.confirmable? && resource.pending_reconfirmation?
		/	| Currently waiting confirmation for: #{resource.unconfirmed_email}
		
		.form-group
			.col-sm-2.control-label
				= f.label :name
			.col-sm-10
				= f.text_field :name, class: "form-control"
		.form-group
			.col-sm-2.control-label
				= f.label :about
			.col-sm-10
				= f.text_area :about, class: "form-control", row: 3
		.form-group
			.col-sm-2.control-label
				= f.label :avatar
			.col-sm-10
				=f.file_field :avatar, class: "form-control"
		- if !@user.avatar.url.nil?
			.form-group
				.col-sm-10.col-sm-offset-2
					= image_tag @user.avatar.url, alt: "user avatar", class: "avatar"
		.form-group
			.col-sm-2.control-label
				= f.label :location
			.col-sm-10
				= f.text_field :location, class: "form-control"
		.form-group
			.col-sm-2.control-label
				= f.label :gender
			.col-sm-10
				= f.select :gender, [['Male', 1], ['Female', 2], ['Other', 3]], {}, class: "form-control"
		.form-group
			.col-sm-2.control-label
				= f.label :birthday
			.col-sm-10
				= f.text_field :birthday, class: "form-control"
		hr
		h4 <b>Change Password</b>
		p.help-block ()(leave blank if you don't want to change it)</i>
		.form-group
			.col-sm-2.control-label
				= f.label :password
			.col-sm-10
				= f.password_field :password, autocomplete: "off", class: "form-control"
		.form-group
			.col-sm-2.control-label
				= f.label :password_confirmation
			.col-sm-10
				= f.password_field :password_confirmation, autocomplete: "off", class: "form-control"
		.bs-callout.bs-callout-warning
			p <b>Current Password</b> <i>(we need your current password to confirm your changes)</i>
			= f.password_field :current_password, autocomplete: "off", class: "form-control"
		.actions
			= f.submit "Update", class: "btn btn-primary-2 btn-block"

app/views/users/_notifications.html.slim
.tab-pane#user_notifications
	- unless (invitations = current_user.invitations).count == 0
		- invitations.each do |invitation|
			.row.user_notification
				.col-md-4
					| Invitation
				.col-md-8
					| Your have been invited by 
					= link_to (user = User.find(invitation.sender_id)).name, user_path(user)
					|  to debate on 
					= link_to (opinion = Debate.find(invitation.debate_id).opinion).title, opinion_path(opinion)
	- else
		p You have no notifications.

app/views/users/_opinions.html.slim
.tab-pane#user_opinions
	- unless (opinions = @user.opinions).count == 0
		- opinions.each do |opinion|
			.row.user_opinion
				.col-md-1
					= link_to (image_tag opinion.image.url, class: "img-thumbnail"), opinion
				.col-md-7
					= link_to opinion.title, opinion
				.col-md-4
					= opinion.created_at
			hr
	- else
		-if current_user.id == @user.id
			p You have no opinions.
		- else
			p The user has no opinions.

app/views/users/_profile.html.slim
.tab-pane#user_profile.active
	- if can? :update, @user
		.btn-toolbar#profile-controls.push-right
			.btn-group
				= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary-2"

	#user_profile

		h4.about About
		pre.about = check_and_fill(@user.about)

		h4.location Location
		pre.location = check_and_fill(@user.location)

		h4.gender Gender
		pre.gender = check_and_fill(@user.gender)

		h4.birthday Birthday
		pre.birthday = check_and_fill(@user.birthday)

app/views/users/edit.html.slim
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				h1 Edit Profile
			.panel-body.padding
				- if can? :edit, @user
					= render 'form'
			.panel-footer					
				.h3 Unhappy? 
				= button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-default"
				= link_to "Back", :back, class: "btn btn-default"

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading.user-heading
				.user-avatar
					= image_tag @user.display_avatar, class: "avatar"
				.user-name
					= @user.name
			.panel-body
				ul.nav.nav-tabs data-tabs="tabs"
					li.tab.active: a href="#user_profile" data-toggle="tab" Profile
					li.tab: a href="#user_opinions" data-toggle="tab" Opinions
					li.tab: a href="#user_debates" data-toggle="tab" Debates
					li.tab: a href="#user_comments" data-toggle="tab" Comments
					li.tab: a href="#user_notifications" data-toggle="tab" Notifications

			.panel-body.user.padding
				.tab-content
					= render 'profile'
					= render 'opinions'
					= render 'debates'
					= render 'comments'
					= render 'notifications'