config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  scope '/admin' do
    resources :users, except: :show
    resources :comments, only: :index
  end
  
  get 'categories/add', to: 'categories#add'
  post 'categories/:id/create', to: 'categories#create'

  resources :categories
  resources :comments, except: [:new, :index]

  delete 'comment/:id/delete' => 'comments#destroy', as: 'delete_comment'

  post "vote/vote" => "votes#vote", as: "vote_opinion"
  patch 'debates/comment/:id/disable' => 'comments#disable', as: 'disable_comment'
  patch 'opinions/:id/disable' => 'opinions#disable', as: 'disable_opinion'

    # resources :debates do
    #   resources :opinions do
    #   	resources :comments
    #   end
    # end
  get 'search', to: 'search#search'
  
  resources :opinions do
    
    post 'create'
    collection do
      get 'search_image'
      post 'query_image'
    end

    resources :debates
  end
  
  resources :debates do
    resources :hoojahs, except: [:index]
  end
  
  # get 'opinions/:opinion_id/debates' => 'debates#new', as: 'new_opinion_debate'  
  # post 'opinions/:opinion_id/debates' => 'debates#create'
  # get 'opinions/:opinion_id/debates/:id' => 'debates#edit', as: 'edit_opinion_debate'

  
  root 'opinions#index'
end

app/models/debate.rb
class Debate < ActiveRecord::Base
	belongs_to :opinion
	has_many :users
	has_many :hoojahs

	def user_pro
		User.find(self.user_pro_id)
	end

	def user_con
		User.find(self.user_con_id)
	end

	def current_hoojah
		self.hoojahs.count
	end
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
	# before_action :authenticate_user!
	before_action :find_opinion, only: [:new, :create, :show, :destroy]
	before_action :find_debate, only: [:show, :disable, :destroy]

	def disable
	  if @debate.hide
      respond_to do |format|
        format.html {redirect_to @opinion, notice: "The comment from #{@comment.user.name} is now hidden."}
        format.js
      end
    end
	end

	def new
		@debate = Debate.new
	end

	def create
		@debate = @opinion.debates.new(post_params)
		if @debate.user_pro_id.nil?
			@debate.user_pro_id = User.find_by(name: params[:challenger]).id
		elsif @debate.user_con_id.nil?
			@debate.user_con_id = User.find_by(name: params[:challenger]).id
		end

		if @debate.save
			redirect_to [@opinion, @debate], notice: 'Invitation sent!'
			user = User.find(@debate.user_con_id)
			user.invitations.create(sender_id: current_user.id, debate_id: @debate.id)
		else
			render 'edit'
		end
	end

	def edit
		@debate = find_debate
	end

	def destroy
	  if @debate.destroy
	    respond_to do |format|
	      format.html {redirect_to @opinion, notice: "You've deleted a debate from #{@debate.user.name}."}
	  	  format.js
	    end
	  end
	end

	def show
		@comments = Comment.where(opinion_id: @opinion)
		@comment = Comment.new
	end

	private

	def find_opinion
		@opinion = Opinion.find(params[:opinion_id])
	end

	def find_debate
		@debate = Debate.find(params[:id])
	end

	def post_params
		params.require(:debate).permit(:opinion_id, :user_pro_id, :user_con_id, :deadline, :winner_id, :disable, :description)
	end
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/views/debates/_form.html.slim
= form_for [@opinion, @debate] do |f|
	/ Display error messages if any
	- if @debate.errors.any?
		#error_explanation
			h2
			= pluralize(@debate.errors.count, "error")
			|	prevented this post from saving
			ul
				- @debate.errors.full_messages.each do |msg|
					li = msg
	

	h2.text-center
		= @opinion.title

	.form-horizontal
		.form-group
			.col-sm-2.control-label
				= label_tag :challenger
			.col-sm-10
				= text_field_tag :challenger, "#{@challenger}", autofocus: true, class: "form-control"
		= f.hidden_field :opinion_id, value: "#{@opinion.id}"
		.form-group
			.col-sm-2.control-label
				= f.label :description
			.col-sm-10
				= f.text_area :description, class: "form-control"
		- if @opinion.voted?(current_user.id)
			- if @opinion.votes.find_by(user_id: current_user.id).flag == 1
				= f.hidden_field :user_pro_id, value: "#{current_user.id}"
				.btn-group
					= f.submit 'Create', class: "btn btn-primary-2 btn-block"
			- elsif @opinion.votes.find_by(user_id: current_user.id).flag == 2
				= f.hidden_field :user_con_id, value: "#{current_user.id}"
				.btn-group
					= f.submit 'Create', class: "btn btn-primary-2 btn-block"
			- else
				p
				| You cannot start a debate with a neutral vote. Please change your vote to #{@opinion.option1} or #{@opinion.option2}
		- else
				p
				| You cannot start a debate without voting. Please change your vote to #{@opinion.option1} or #{@opinion.option2}

app/views/debates/new.html.slim
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				h1 Add new debate
			.panel-body.padding
				- if can? :create, @debate
					= render 'form'
				- else
					  p
					  	| You must #{link_to "Login", new_user_session_path} to create a new debate

app/views/debates/show.html.slim
#debate_show.row
	.col-md-2
		.fixed-outer.col-md-2
			.fixed.col-md-2.fix-padding-left
				.bg-blue.user.center.white
					br
					.picture
						= image_tag @debate.user_pro.display_avatar, alt: "#{@debate.user_pro.name}'s avatar"
					p = @debate.user_pro.name
					span.glyphicon.glyphicon-bullhorn
					|	&nbsp
					= pluralize(@debate.user_pro.debates_count, "debate")
					br
					span.glyphicon.glyphicon-comment
					|	&nbsp
					= pluralize(@debate.user_pro.opinions_count, "opinion")
					br
					span.glyphicon.glyphicon-edit
					|	&nbsp
					= pluralize(@debate.user_pro.votes_count, "vote")
					br
					- if can? :create, @hoojah && @debate.user_pro.id == current_user.id
						- if @debate.current_hoojah%2 == 0
							= link_to "Add your hoojah", new_debate_hoojah_path(@debate), class: "btn btn-default"
					br
	.col-md-8
		.panel.panel-default
			.panel-heading.opinion_image
				#image-border
					.btn-toolbar.btn-group.debate-edit-delete
						- if can? :update, @debate
							= link_to edit_comment_path(@debate), class: "btn btn-default" do
									<span class="glyphicon glyphicon-pencil"></span>
							= link_to disable_comment_path(@debate), class: "btn btn-default", method: :patch, data: {confirm: "Are you sure you want to delete this debate?"} do
								<span class="glyphicon glyphicon-trash"></span>
						- if can? :destroy, @debate
							= link_to [@opinion, @debate], class: "btn btn-danger", method: :delete, data: {confirm: "(Admin) Are you sure you want to delete this debate (for real)?"} do
								<span class="glyphicon glyphicon-remove"></span>
					- if @opinion.image.url.nil?
						= link_to (image_tag "default_image.png"), @opinion
					- else
						= link_to (image_tag @opinion.image_url), @opinion 
				.panel-title
					.panel-container
						h2.text-center
							= @opinion.title
						.panel-vote
							= link_to @opinion.option1, vote_opinion_path(id: @opinion.id, flag: 1), method: :post, class: "option1"
							= link_to "Neutral", vote_opinion_path(id: @opinion.id, flag: 0), method: :post, class: "neutral"
							= link_to @opinion.option2, vote_opinion_path(id: @opinion.id, flag: 2), method: :post, class: "option2"
			.panel-body
				- unless @opinion.votes.all.empty?
					.percentage-bar.text-center
						- if @opinion.vote_1.count != nil && @opinion.vote_1.count > 0
							<span style="width: #{(@opinion.vote_1.count) == nil ? 0 : (@opinion.vote_1.count).percentage_of(@opinion.votes.count)}%;" class="opinion1-bar bg-blue">#{(@opinion.vote_1.count) == nil ? 0 : (@opinion.vote_1.count).percentage_of(@opinion.votes.count).round(2)}%</span>
						- if @opinion.vote_0.count != nil && @opinion.vote_0.count > 0
							<span style="width: #{(@opinion.vote_0.count) == nil ? 0 : (@opinion.vote_0.count).percentage_of(@opinion.votes.count)}%;" class="neutral-bar bg-orange">#{(@opinion.vote_0.count) == nil ? 0 : (@opinion.vote_0.count).percentage_of(@opinion.votes.count).round(2)}%</span>
						- if @opinion.vote_2.count != nil && @opinion.vote_2.count > 0
							<span style="width: #{(@opinion.vote_2.count) == nil ? 0 : (@opinion.vote_2.count).percentage_of(@opinion.votes.count)}%;" class="opinion2-bar bg-green">#{(@opinion.vote_2.count) == nil ? 0 : (@opinion.vote_2.count).percentage_of(@opinion.votes.count).round(2)}%</span>
			/ .panel-heading
			/ 	.row
			/ 		.col-md-4
			/ 			.comments
			/ 				= @debate.user_pro.name
			/ 		.col-md-1.comments
			/ 			span.picture
			/ 				= image_tag @debate.user_pro.display_avatar, alt: "#{@debate.user_pro.name}'s avatar", class: 'picture-1'
			/ 		.col-md-2
			/ 			h4.text-center VS
			/ 		.col-md-1
			/ 			.comments
			/ 				span.picture
			/ 					= image_tag @debate.user_con.display_avatar, alt: "#{@debate.user_con.name}'s avatar", class: 'picture-2'
			/ 		.col-md-4
			/ 			= @debate.user_con.name
			.panel-footer	
				p Opinion posted by <a href="#{user_path(@opinion.user)}">#{@opinion.user.name}</a> #{time_ago_in_words(@opinion.created_at)} ago
				p = @debate.description
			- unless @debate.hoojahs.empty?
				- @debate.hoojahs.each_with_index do |hoojah, index|
					- if index%2 == 0
						.panel-body.padding.hoojah.hoojah-blue
							.hoojah-timestamp.bg-blue.hoojah-timestamp-left
								| Written #{time_ago_in_words(hoojah.created_at)} ago
							.hoojah-text = simple_format(hoojah.body)
					- else
						.panel-body.padding.hoojah.hoojah-green
							.hoojah-timestamp.bg-green.hoojah-timestamp-right
								| Written #{time_ago_in_words(hoojah.created_at)} ago
							.hoojah-text = simple_format(hoojah.body)
					br

			.panel-body.padding
				- if can? :create, @comment
					= render 'comments/form'
				- else
					p
					| You must #{link_to "Login", new_user_session_path} before you can comment
		    ol.comments
			  	= render @comments
	.fixed-outer.col-md-2
		.fixed.col-md-2.fix-padding-right
			.bg-green.user.center.white
				br
				.picture
					= image_tag @debate.user_con.display_avatar, alt: "#{@debate.user_con.name}'s avatar"
				p = @debate.user_con.name
				span.glyphicon.glyphicon-bullhorn
				|	&nbsp
				= pluralize(@debate.user_con.debates_count, "debate")
				br
				span.glyphicon.glyphicon-comment
				|	&nbsp
				= pluralize(@debate.user_con.opinions_count, "opinion")
				br
				span.glyphicon.glyphicon-edit
				|	&nbsp
				= pluralize(@debate.user_con.votes_count, "vote")
				br
				- if can? :create, @hoojah && @debate.user_pro.id == current_user.id
					- if @debate.current_hoojah%2 != 0
						= link_to "Add your hoojah", new_debate_hoojah_path(@debate), class: "btn btn-default"
				br