config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  scope '/admin' do
    resources :users, except: :show
    resources :comments, only: :index
  end
  
  get 'categories/add', to: 'categories#add'
  post 'categories/:id/create', to: 'categories#create'

  resources :categories
  resources :comments, except: [:new, :index]

  delete 'comment/:id/delete' => 'comments#destroy', as: 'delete_comment'

  post "vote/vote" => "votes#vote", as: "vote_opinion"
  patch 'debates/comment/:id/disable' => 'comments#disable', as: 'disable_comment'
  patch 'opinions/:id/disable' => 'opinions#disable', as: 'disable_opinion'

    # resources :debates do
    #   resources :opinions do
    #   	resources :comments
    #   end
    # end
  get 'search', to: 'search#search'
  
  resources :opinions do
    
    post 'create'
    collection do
      get 'search_image'
      post 'query_image'
    end

    resources :debates
  end
  
  resources :debates do
    resources :hoojahs, except: [:index]
  end
  
  # get 'opinions/:opinion_id/debates' => 'debates#new', as: 'new_opinion_debate'  
  # post 'opinions/:opinion_id/debates' => 'debates#create'
  # get 'opinions/:opinion_id/debates/:id' => 'debates#edit', as: 'edit_opinion_debate'

  
  root 'opinions#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<%= link_to 'hoojah', root_path, alt: "hoojah", class: "navbar-brand" %>
			<button class="navbar-toggle" data-toggle="collapse" data-target=".nav-header-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="navbar-collapse collapse nav-header-collapse">
			<!--%= form_for search_path, html: {class: "navbar-form navbar-search-input"}, method: :get do |f| %>
				%= text_field_tag :query, params[:query], class: 'form-control', placeholder: "Search" %>
			% end %-->
			<ul class="nav navbar-nav pull-right">
				<% if user_signed_in? %>
					<li class="navbar-top-link"><%= link_to 'New Opinion', new_opinion_path %></li>
					<% if current_user.avatar_url.nil? %>
						<li><%= link_to (image_tag "default_avatar.png", alt: "#{current_user.name}'s Profile", class: 'navbar-avatar'), current_user %></li>
					<% else %>
						<li class="navbar-top-link"><%= link_to image_tag(current_user.avatar_url, alt: "#{current_user.name}'s Profile", class: 'navbar-avatar'), current_user %></li> 
					<% end %>
					<li class="navbar-top-link"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li class="navbar-top-link"><%= link_to 'Sign Up', new_user_registration_path %></li>
					<li class="navbar-top-link"><%= link_to 'Sign In', new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>			

app/views/layouts/_navbar_white.html.slim
.row.nav-white-top
	.col-md-4
			= link_to (image_tag "logo-colour.png", alt: "hoojah", class: "logo"), root_path

app/views/layouts/_search.html.slim
= form_for search_path, method: :get do |f|
  = text_field_tag :q, params[:q]
  = submit_tag image_tag, name: nil

- unless @opinions.nil?
  h4 Here are your results:
  - @opinions.each do |opinion|
    li
      h
        = link_to opinion.title, controller: "opinions", action: "show", id: opinion.id

app/views/layouts/application.html.slim
doctype 5

html

	head
		meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
		title hoojah	
		= stylesheet_link_tag 		'application', media: 'all', 'data-turbolinks-track' => true
		/ = javascript_include_tag	'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
		/ = javascript_include_tag  'assets/js/twitterbootstrap/js/bootstrap-tab.js'
		/ = javascript_include_tag	'assets/js/freewall.js'

	body
		- unless @js_custom_turbolink.nil?
			= javascript_include_tag  'application', media: 'all', data: @custom_turbolink
		- else
			= javascript_include_tag 'application', data: {'turbolinks-track' => true}

		= render 'layouts/navbar'
		
		.container
			- if notice
				<div class="alert alert-info" role="alert">#{notice}</div>
			- if alert
				<div class="alert alert-success" role="alert">#{alert}</div>
			#page
				= yield
		#footer.navbar.navbar-static-bottom
			.container
				.row
					.col-md-3
						= link_to 'hoojah', root_path, alt: "hoojah", class: "navbar-brand"
						.clearfix
						.navbar-footer-link
							br
							| hoojah is a free online community where intelligent minds from around the world come to debate and read the opinions of others. Research today’s most controversial debate topics and contribute by voting.
							br
							br
							<a href="#">Privacy Policy</a> | <a href="#">Term of Use</a> | <a href="#">Sitemap</a>
					.col-md-3
						h3 Popular Categories
						ul.list-group
							- @categories.first(5).each_with_index do |category, index|
								- if index < 4
									li.list-group-item.footer = category.name
								- else
									li.list-group-item.footer-no-bottom = category.name
					.col-md-3
						h3 Popular Tags
						ul.list-group
							- @categories.first(5).each_with_index do |category, index|
								- if index < 4
									li.list-group-item.footer = category.name
								- else
									li.list-group-item.footer-no-bottom = category.name
					.col-md-3
						h3 Follow us!
						= image_tag "social_icons.png", width: "300px"